# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Topics
    url: tags/
    weight: 20
  - name: About
    url: about/
    weight: 30
  - name: Uses
    url: uses/
    weight: 40
  - name: Contact
    url: contact/
    weight: 50
    